---
- name: Set variable overrides
  ansible.builtin.set_fact:
    _acme_certificate_packages: "{{ acme_certificate_packages | default(_packages_default) }}"
    _acme_certificate_storedir: "{{ acme_certificate_storedir | default(acme_certificate_storedir_default) }}"
  vars:
    overrides:
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}"
      - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version }}"
      - "{{ ansible_distribution | lower }}"
      - "{{ ansible_os_family | lower }}"
      - "default"
    _storedir_default: "{{ (ansible_os_family == 'Debian') | ternary(acme_certificate_storedir_debian, acme_certificate_storedir_redhat) }}"
    _packages_default: "{{ acme_certificate_packages_default | sorted_get(overrides) }}"
  tags: always

- name: Install package requirements
  ansible.builtin.package:
    name: "{{ _acme_certificate_packages }}"

- name: Install pip requirements
  ansible.builtin.pip:
    name: cryptography
  changed_when: false
  when: ansible_os_family == 'RedHat'

- name: Create acme group
  ansible.builtin.group:
    name: "{{ acme_certificate_group }}"

- name: Add users to acme group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: "{{ acme_certificate_group }}"
    append: yes
  loop: "{{ acme_certificate_group_members | flatten(levels=1) }}"

- name: Create acme folders
  ansible.builtin.file:
    path: "{{ item }}"
    mode: "u=rwx,go=rx"
    state: directory
    group: "{{ acme_certificate_group }}"
  loop:
    - "{{ acme_certificate_certdir }}"
    - "{{ acme_certificate_keydir }}"

- name: Create account key
  community.crypto.openssl_privatekey:
    path: "{{ acme_certificate_account_keyfile }}"
    owner: root
    group: "{{ acme_certificate_group }}"
    mode: "u=rw,g=r,o="

- name: Create domain key
  community.crypto.openssl_privatekey:
    path: "{{ _acme_certificate_domain_keyfile }}"
    owner: root
    group: "{{ acme_certificate_group }}"
    mode: "u=rw,g=r,o="

- name: Create csr
  community.crypto.openssl_csr:
    path: "{{ _acme_certificate_domain_csrfile }}"
    privatekey_path: "{{ _acme_certificate_domain_keyfile }}"
    common_name: "{{ acme_certificate_domain }}"

- name: Create acme challenge
  community.crypto.acme_certificate:
    account_key: "{{ acme_certificate_account_keyfile }}"
    challenge: dns-01
    csr: "{{ _acme_certificate_domain_csrfile }}"
    dest: "{{ _acme_certificate_domain_crtfile }}"
    fullchain_dest: "{{ _acme_certificate_domain_chainfile }}"
    terms_agreed: yes
    acme_version: "{{ acme_certificate_api_version }}"
    acme_directory: "{{ acme_certificate_directory }}"
  register: acme_certificate_challenge

- name: Validate acme challenge
  when: acme_certificate_challenge is changed
  block:
    - name: Create route53 txt record for certificate validation
      amazon.aws.route53:
        command: create
        aws_access_key: "{{ acme_certificate_aws_accesskey_id }}"
        aws_secret_key: "{{ acme_certificate_aws_accesskey_secret }}"
        zone: "{{ acme_certificate_zone }}"
        type: TXT
        record: '{{ acme_certificate_challenge.challenge_data[acme_certificate_domain]["dns-01"]["record"] }}'
        value: '"{{ acme_certificate_challenge.challenge_data[acme_certificate_domain]["dns-01"]["resource_value"] }}"'
        ttl: "{{ acme_certificate_challenge_ttl }}"
        wait: yes
        overwrite: yes
      retries: 5
      delay: 60
      register: acme_validation
      until: acme_validation is succeeded

    - name: Wait for txt record replication
      ansible.builtin.pause:
        seconds: "{{ acme_certificate_challenge_wait }}"

    - name: Validate challenge
      community.crypto.acme_certificate:
        account_key: "{{ acme_certificate_account_keyfile }}"
        challenge: dns-01
        csr: "{{ _acme_certificate_domain_csrfile }}"
        dest: "{{ _acme_certificate_domain_crtfile }}"
        fullchain_dest: "{{ _acme_certificate_domain_chainfile }}"
        data: "{{ acme_certificate_challenge }}"
        terms_agreed: yes
        acme_directory: "{{ acme_certificate_directory }}"
        acme_version: "{{ acme_certificate_api_version }}"
      delay: "{{ acme_certificate_challenge_ttl }}"

  always:
    - name: Delete route53 txt record for certificate validation
      amazon.aws.route53:
        command: delete
        aws_access_key: "{{ acme_certificate_aws_accesskey_id }}"
        aws_secret_key: "{{ acme_certificate_aws_accesskey_secret }}"
        zone: "{{ acme_certificate_zone }}"
        type: TXT
        record: '{{ acme_certificate_challenge.challenge_data[acme_certificate_domain]["dns-01"]["record"] }}'
        value: '"{{ acme_certificate_challenge.challenge_data[acme_certificate_domain]["dns-01"]["resource_value"] }}"'
        ttl: "{{ acme_certificate_challenge_ttl }}"
        wait: yes
      retries: 5
      delay: 60
      register: acme_validation
      until: acme_validation is succeeded

- name: Retrieve acme root ca file
  ansible.builtin.get_url:
    url: "{{ acme_certificate_caurl }}"
    dest: "{{ acme_certificate_certdir }}/{{ _acme_certificate_cafile }}"
    mode: "u=rw,g=r,o=r"

- name: Retrieve acme intermediate ca file
  ansible.builtin.get_url:
    url: "{{ acme_certificate_intcaurl }}"
    dest: "{{ acme_certificate_certdir }}/{{ _acme_certificate_intcafile }}"
    mode: "u=rw,g=r,o=r"

- name: Configure local certificate chain
  when: acme_certificate_add_ca | bool
  block:
    - name: Create acme ca root dir
      ansible.builtin.file:
        state: directory
        mode: "u=rwx,g=rx,o="
        dest: "{{ _acme_certificate_storedir }}"

    - name: Copy acme root ca file to trust store
      ansible.builtin.copy:
        mode: preserve
        remote_src: yes
        src: "{{ acme_certificate_certdir }}/{{ _acme_certificate_cafile }}"
        dest: "{{ _acme_certificate_storedir }}/{{ _acme_certificate_cafile }}"

    - name: Update ca certificates
      ansible.builtin.command: update-ca-certificates
      changed_when: false
      when: ansible_os_family == 'Debian'

    - name: Update ca certificates
      ansible.builtin.command: update-ca-trust extract
      changed_when: false
      when: ansible_os_family == 'RedHat'

- name: Set certificate file link
  ansible.builtin.file:
    state: link
    src: "{{ _acme_certificate_domain_crtfile }}"
    dest: "{{ acme_certificate_certfile }}"
  when: acme_certificate_certfile is defined

- name: Set certificate chain link
  ansible.builtin.file:
    state: link
    src: "{{ _acme_certificate_domain_chainfile }}"
    dest: "{{ acme_certificate_chainfile }}"
  when: acme_certificate_chainfile is defined

- name: Set certificate key link
  ansible.builtin.file:
    state: link
    src: "{{ _acme_certificate_domain_keyfile }}"
    dest: "{{ acme_certificate_keyfile }}"
  when: acme_certificate_keyfile is defined

- name: Set ca file link
  ansible.builtin.file:
    state: link
    src: "{{ acme_certificate_certdir }}/{{ _acme_certificate_cafile }}"
    dest: "{{ acme_certificate_cafile }}"
  when: acme_certificate_cafile is defined

- name: Set intca file link
  ansible.builtin.file:
    state: link
    src: "{{ acme_certificate_certdir }}/{{ _acme_certificate_intcafile }}"
    dest: "{{ acme_certificate_intcafile }}"
  when: acme_certificate_intcafile is defined
