---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: centos7
    image: centos:7
  - name: xenial
    image: ubuntu:xenial
  - name: bionic
    image: ubuntu:bionic
  - name: stretch
    image: debian:stretch
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    group_vars:
      all:
        acme_certificate_directory: https://acme-staging.api.letsencrypt.org/directory
        acme_certificate_email: ci@nephelai.io
        acme_certificate_domain: "{{ ansible_hostname }}.nephelai.io"
        acme_certificate_caurl: https://letsencrypt.org/certs/fakelerootx1.pem
        acme_certificate_intcaurl: https://letsencrypt.org/certs/fakeleintermediatex1.pem
        acme_certificate_cafile: /tmp/cafile
        acme_certificate_intcafile: /tmp/intfile
        acme_certificate_chainfile: /tmp/chainfile
        acme_certificate_file: /tmp/crtfile
        acme_certificate_keyfile: /tmp/keyfile
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
