---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}-ansible:latest"
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: false
    pre_build_image: true
    cgroupns_mode: private
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        acme_certificate_directory: https://acme-staging-v02.api.letsencrypt.org/directory
        acme_certificate_email: ci@nephelai.io
        acme_certificate_domain: "route53-${MOLECULE_DOCKER_IMAGE:-ubuntu2204}.home.nephelai.io"
        acme_certificate_aws_accesskey_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
        acme_certificate_aws_accesskey_secret: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
        acme_certificate_cafile: /tmp/cafile
        acme_certificate_chainfile: /tmp/chainfile
        acme_certificate_certfile: /tmp/crtfile
        acme_certificate_keyfile: /tmp/keyfile
scenario:
  name: default
verifier:
  name: ansible
