---
name: lint

on:
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: 'nephelaiio.acme_certificate_route53'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: 'nephelaiio.acme_certificate_route53'

      - name: Set up Python 3.
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Update ubuntu repositories
        run: sudo apt-get update

      - name: Install make
        run: sudo apt-get install -y make

      - name: Lint code
        run: make lint
