---
name: molecule

on:
  pull_request:
    branches:
      - master

defaults:
  run:
    working-directory: 'nephelaiio.acme_certificate_route53'

jobs:

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - ubuntu2204
          - ubuntu2004
          - ubuntu1804
          - debian11
          - debian10
          - rockylinux9
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'nephelaiio.acme_certificate_route53'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-ve rsion: '3.x'

      - name: Install poetry
        run: pip3 install poetry

      - name: Install pips
        run: poetry install

      - name: Run Molecule tests.
        run: poetry run molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DOCKER_IMAGE: ${{ matrix.image }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
